select 'ALTER TABLE ' ||OWNER||'.'||TABLE_NAME|| ' MOVE TABLESPACE TS_SATP_DAT_TMP;'
FROM DBA_TABLES
WHERE TABLESPACE_NAME = 'TS_SATP_DAT_1M';


SELECT 'ALTER INDEX '||OWNER||'.'||INDEX_NAME|| ' REBUILD;'
FROM DBA_INDEXES
WHERE STATUS <> 'VALID';


select 'ALTER INDEX ' ||OWNER||'.'||INDEX_NAME|| ' REBUILD
TABLESPACE TS_SATP_IDX_64K;'
FROM DBA_INDEXES
WHERE TABLESPACE_NAME = 'TS_SATP_DAT_64K'


CREATE TABLESPACE "TS_SATP_DAT_10M" 
LOGGING 
DATAFILE 'I:\ORADATA\SATP\TS_SATP_DAT_10M_01.DBFF' SIZE 2000M 
REUSE EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10240K SEGMENT 
SPACE MANAGEMENT  MANUAL 


select 'ALTER TABLE ' ||OWNER||'.'||SEGMENT_NAME|| ' MOVE TABLESPACE TS_SATP_DAT_1M;'
from dba_segments
where TABLESPACE_NAME = 'TS_SATP_DAT_TMP'
ORDER BY trunc(bytes/1024/1024);

