CREATE TABLE "DBADMIN"."CRESCIMENTO_DATABASE" ("TIME" DATE, 
    "TABLESPACE_NAME" VARCHAR2(30), "DATAFILE_NAME" VARCHAR2(257),
    "BYTES" NUMBER, "FREE_BYTES" NUMBER)  
    TABLESPACE "USERS" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 
    255 
    STORAGE ( INITIAL 256K NEXT 256K MINEXTENTS 1 MAXEXTENTS 
    2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1) 
    LOGGING 